# Generated by Django 5.2.6 on 2025-09-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
